### ISSUE TITLE
Add Github hacs topic

### ISSUE THREAD

**Issue by ThomDietrich** [mammuth/ha-fritzbox-tools#76]
https://github.com/topics/hacs

**Comment by mammuth** [comment]
Thanks for the hint.

**Comment by ThomDietrich** [comment]
I'm confused. You still didn't add it, did you?

![image](https://user-images.githubusercontent.com/2870104/77404719-743d4480-6db2-11ea-8405-dd5eaf753353.png)

**Comment by mammuth** [comment]
I didn't add it.

In my opinion most of the custom components should be integrated in core which would benefit the users from code reviews, better quality and maintenance (and also benefits the developer with eg unified dependencies, an issue we're facing in this component).

On the one hand HACS is beneficial for users because they can easily get functionality which isn't in core yet, on the other hand this leads to an increased number of custom components never reaching core (or at least taking way longer, look at this component) and sometimes frustration due to bad implementations or dependency conflicts.

Overall I'm not a big fan of HACS because of the mentioned trade-off and the goal for this integration is to move it into core.
We needed some time to implement and test the features (where HACS obviously helped us reaching more testers), but we actually might be ready to integrate it.

I hope you understand my reasoning. :blush:

**Comment by ThomDietrich** [comment]
Excellent. I'm also unhappy with the current situation as you described it and would love to see a development here. (Whether or not your "protest" is meaningful could still be debated but I understand the general reasoning :)
